"""Email delivery service — sends HTML summaries via Resend."""

from __future__ import annotations

import re
import resend

from app.config import settings

# Minimal HTML email template with inline CSS for max compatibility
_EMAIL_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f4f4f7;font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <div style="max-width:640px;margin:32px auto;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:32px 40px;">
      <h1 style="margin:0;color:#ffffff;font-size:22px;font-weight:700;">
        🐇 Rabbitt AI — Sales Insight Brief
      </h1>
      <p style="margin:8px 0 0;color:#e0e7ff;font-size:14px;">{subject}</p>
    </div>
    <!-- Body -->
    <div style="padding:32px 40px;color:#1e293b;font-size:15px;line-height:1.7;">
      {body_html}
    </div>
    <!-- Footer -->
    <div style="padding:20px 40px;background:#f8fafc;border-top:1px solid #e2e8f0;text-align:center;">
      <p style="margin:0;color:#94a3b8;font-size:12px;">
        Generated by <strong>Rabbitt AI Sales Insight Automator</strong><br>
        This is an automated report — please do not reply.
      </p>
    </div>
  </div>
</body>
</html>
"""


def _markdown_to_html(md: str) -> str:
    """Convert basic markdown to HTML for email rendering."""
    html = md

    # Headers
    html = re.sub(r"^### (.+)$", r"<h3 style='color:#4f46e5;margin:24px 0 8px;'>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^## (.+)$", r"<h2 style='color:#4f46e5;margin:24px 0 8px;'>\1</h2>", html, flags=re.MULTILINE)
    html = re.sub(r"^# (.+)$", r"<h1 style='color:#4f46e5;margin:24px 0 8px;'>\1</h1>", html, flags=re.MULTILINE)

    # Bold & italic
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)

    # Bullet lists
    html = re.sub(r"^[-*] (.+)$", r"<li style='margin:4px 0;'>\1</li>", html, flags=re.MULTILINE)
    html = re.sub(r"(<li[^>]*>.*?</li>\n?)+", r"<ul style='padding-left:20px;'>\g<0></ul>", html)

    # Paragraphs (double newline)
    paragraphs = html.split("\n\n")
    processed = []
    for p in paragraphs:
        p = p.strip()
        if not p:
            continue
        if p.startswith("<h") or p.startswith("<ul") or p.startswith("<li"):
            processed.append(p)
        else:
            processed.append(f"<p style='margin:12px 0;'>{p}</p>")
    html = "\n".join(processed)

    # Single newlines → <br>
    html = re.sub(r"(?<!</li>)\n(?!<)", "<br>\n", html)

    return html


async def send_summary_email(
    to_email: str,
    summary_markdown: str,
    subject: str = "Q1 2026 Sales Insight Brief — Rabbitt AI",
) -> dict:
    """
    Send the AI-generated summary as a branded HTML email.

    Returns the Resend API response.
    """
    resend.api_key = settings.resend_api_key

    body_html = _markdown_to_html(summary_markdown)
    full_html = _EMAIL_TEMPLATE.format(subject=subject, body_html=body_html)

    params: resend.Emails.SendParams = {
        "from": settings.from_email,
        "to": [to_email],
        "subject": subject,
        "html": full_html,
        "text": summary_markdown,  # plain-text fallback
    }

    email_response = resend.Emails.send(params)
    return email_response
