"""Enhanced email service — branded HTML with inline charts, SMTP fallback, retry logic."""

from __future__ import annotations

import asyncio
import base64
import os
import re
import smtplib
import time
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

import resend

from app.config import settings
from app.logging_config import get_logger

logger = get_logger(__name__)

# ── HTML template with CID image placeholders ──
_EMAIL_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f4f4f7;font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <div style="max-width:680px;margin:32px auto;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
    <div style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:32px 40px;">
      <h1 style="margin:0;color:#ffffff;font-size:22px;font-weight:700;">
        🐇 Rabbitt AI — Sales Insight Brief
      </h1>
      <p style="margin:8px 0 0;color:#e0e7ff;font-size:14px;">{subject}</p>
    </div>
    <div style="padding:32px 40px;color:#1e293b;font-size:15px;line-height:1.7;">
      <h2 style="color:#4f46e5;margin:0 0 12px;">Executive Summary</h2>
      <p style="margin:0 0 20px;">{executive_summary}</p>
      <h2 style="color:#4f46e5;margin:24px 0 12px;">Key Trends</h2>
      <ul style="padding-left:20px;margin:0 0 20px;">{key_trends_html}</ul>
      <h2 style="color:#4f46e5;margin:24px 0 12px;">Regional Analysis</h2>
      <p style="margin:0 0 20px;">{regional_analysis}</p>
      <h2 style="color:#4f46e5;margin:24px 0 12px;">Product Insights</h2>
      <p style="margin:0 0 20px;">{product_insights}</p>
      {anomalies_section}
      {charts_html}
      <h2 style="color:#4f46e5;margin:24px 0 12px;">Recommendations</h2>
      <ul style="padding-left:20px;margin:0 0 20px;">{recommendations_html}</ul>
    </div>
    <div style="padding:20px 40px;background:#f8fafc;border-top:1px solid #e2e8f0;text-align:center;">
      <p style="margin:0;color:#94a3b8;font-size:12px;">
        Generated by <strong>Rabbitt AI Sales Insight Automator</strong><br>
        This is an automated report — please do not reply.
      </p>
    </div>
  </div>
</body>
</html>
"""


def _build_html(brief: dict[str, Any], subject: str, chart_paths: list[str] | None = None) -> str:
    """Build the full HTML email from the structured brief."""
    key_trends = brief.get("key_trends", [])
    key_trends_html = "".join(
        f'<li style="margin:4px 0;">{t}</li>' for t in key_trends
    )

    recommendations = brief.get("recommendations", [])
    recommendations_html = "".join(
        f'<li style="margin:4px 0;">{r}</li>' for r in recommendations
    )

    anomalies = brief.get("anomalies", [])
    anomalies_section = ""
    if anomalies:
        items = "".join(f'<li style="margin:4px 0;color:#dc2626;">{a}</li>' for a in anomalies)
        anomalies_section = (
            '<h2 style="color:#dc2626;margin:24px 0 12px;">⚠ Anomalies</h2>'
            f'<ul style="padding-left:20px;margin:0 0 20px;">{items}</ul>'
        )

    charts_html = ""
    if chart_paths:
        charts_html = '<h2 style="color:#4f46e5;margin:24px 0 12px;">📊 Charts</h2>'
        for idx, _path in enumerate(chart_paths):
            charts_html += (
                f'<div style="margin:16px 0;text-align:center;">'
                f'<img src="cid:chart{idx}" style="max-width:100%;border-radius:8px;'
                f'box-shadow:0 2px 8px rgba(0,0,0,0.1);" />'
                f'</div>'
            )

    return _EMAIL_TEMPLATE.format(
        subject=subject,
        executive_summary=brief.get("executive_summary", ""),
        key_trends_html=key_trends_html,
        regional_analysis=brief.get("regional_analysis", ""),
        product_insights=brief.get("product_insights", ""),
        anomalies_section=anomalies_section,
        charts_html=charts_html,
        recommendations_html=recommendations_html,
    )


def _build_plain_text(brief: dict[str, Any]) -> str:
    """Build plain-text fallback from structured brief."""
    parts = [
        "EXECUTIVE SUMMARY",
        brief.get("executive_summary", ""),
        "",
        "KEY TRENDS",
    ]
    parts.extend(f"  - {t}" for t in brief.get("key_trends", []))
    parts.extend(["", "REGIONAL ANALYSIS", brief.get("regional_analysis", "")])
    parts.extend(["", "PRODUCT INSIGHTS", brief.get("product_insights", "")])
    anomalies = brief.get("anomalies", [])
    if anomalies:
        parts.extend(["", "ANOMALIES"])
        parts.extend(f"  ! {a}" for a in anomalies)
    parts.extend(["", "RECOMMENDATIONS"])
    parts.extend(f"  - {r}" for r in brief.get("recommendations", []))
    return "\n".join(parts)


def _read_chart_base64(path: str) -> str:
    """Read a chart file and return base64 encoded string."""
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("ascii")


async def send_summary_email(
    to_email: str,
    brief: dict[str, Any],
    subject: str = "Sales Insight Brief — Rabbitt AI",
    chart_paths: list[str] | None = None,
) -> dict[str, Any]:
    """
    Send the structured brief as a branded HTML email with inline charts.
    Tries Resend first, falls back to SMTP. Retries 2x with exponential backoff.
    """
    last_err: Exception | None = None

    # Try Resend (primary)
    if settings.resend_api_key:
        for attempt in range(3):
            if attempt > 0:
                delay = 2 ** attempt
                logger.info("Resend retry %d/2, backoff %ds", attempt, delay)
                await asyncio.sleep(delay)
            try:
                start = time.perf_counter()
                result = await _send_via_resend(to_email, brief, subject, chart_paths)
                latency = (time.perf_counter() - start) * 1000
                logger.info("Email sent via Resend in %.0fms, id=%s", latency, result.get("id"))
                return result
            except Exception as err:
                last_err = err
                logger.warning("Resend attempt %d failed: %s", attempt + 1, err)

    # Try SMTP (fallback)
    if settings.smtp_host:
        for attempt in range(3):
            if attempt > 0:
                delay = 2 ** attempt
                logger.info("SMTP retry %d/2, backoff %ds", attempt, delay)
                await asyncio.sleep(delay)
            try:
                start = time.perf_counter()
                result = await _send_via_smtp(to_email, brief, subject, chart_paths)
                latency = (time.perf_counter() - start) * 1000
                logger.info("Email sent via SMTP in %.0fms", latency)
                return result
            except Exception as err:
                last_err = err
                logger.warning("SMTP attempt %d failed: %s", attempt + 1, err)

    raise RuntimeError(f"All email providers failed. Last error: {last_err}")


async def _send_via_resend(
    to_email: str,
    brief: dict[str, Any],
    subject: str,
    chart_paths: list[str] | None,
) -> dict[str, Any]:
    """Send via Resend API with base64 inline charts."""
    resend.api_key = settings.resend_api_key
    html = _build_html(brief, subject)
    plain = _build_plain_text(brief)

    # Replace CID references with base64 data URIs for Resend
    if chart_paths:
        for idx, path in enumerate(chart_paths):
            if os.path.isfile(path):
                b64 = _read_chart_base64(path)
                html = html.replace(
                    f'src="cid:chart{idx}"',
                    f'src="data:image/png;base64,{b64}"',
                )

    params: resend.Emails.SendParams = {
        "from": settings.from_email,
        "to": [to_email],
        "subject": subject,
        "html": html,
        "text": plain,
    }

    response = resend.Emails.send(params)
    if isinstance(response, dict):
        return response
    return {"id": getattr(response, "id", None)}


async def _send_via_smtp(
    to_email: str,
    brief: dict[str, Any],
    subject: str,
    chart_paths: list[str] | None,
) -> dict[str, Any]:
    """Send via SMTP with CID-attached chart images."""
    msg = MIMEMultipart("related")
    msg["From"] = settings.from_email
    msg["To"] = to_email
    msg["Subject"] = subject

    alt = MIMEMultipart("alternative")
    msg.attach(alt)

    plain = _build_plain_text(brief)
    alt.attach(MIMEText(plain, "plain", "utf-8"))

    html = _build_html(brief, subject, chart_paths)
    alt.attach(MIMEText(html, "html", "utf-8"))

    # Attach chart images as CID
    if chart_paths:
        for idx, path in enumerate(chart_paths):
            if os.path.isfile(path):
                with open(path, "rb") as f:
                    img = MIMEImage(f.read(), _subtype="png")
                    img.add_header("Content-ID", f"<chart{idx}>")
                    img.add_header("Content-Disposition", "inline", filename=os.path.basename(path))
                    msg.attach(img)

    loop = asyncio.get_event_loop()
    await loop.run_in_executor(None, _smtp_send, msg, to_email)
    return {"id": None, "provider": "smtp"}


def _smtp_send(msg: MIMEMultipart, to_email: str) -> None:
    """Blocking SMTP send, run in executor."""
    with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(settings.smtp_user, settings.smtp_password)
        server.sendmail(settings.from_email, [to_email], msg.as_string())
